# Generated by Django 4.1.1 on 2023-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_customer_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phn_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
