# Generated by Django 4.1.1 on 2023-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_rename_phn_number_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
